version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          # projectname can be anything, so long as it matches save_cache below.
          key: deps0-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip3 install pipenv
            pipenv install -e .[dev] --skip-lock
            pipenv graph
            # The -e .[dev] installs all the regular required packages and those listed in the dev section of `extras_require` in setup.py.
      - save_cache:
          key: deps0-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          name: Running tests
          #pipenv install methylprep --skip-lock
          command: |
            pipenv install coveralls --skip-lock
            pipenv run coverage run setup.py test
      - run:
          name: Coverage
          # pipenv run pytest tests --junit-xml=htmlcov/junit.xml # rerun tests to collect test-results | see setup.cfg
          command: |            
            pipenv run coverage report -i
            pipenv run coverage html -i
            pipenv run coveralls # -- pushes report to coveralls.io
      - store_test_results:
          path: htmlcov
      - store_artifacts:
          path: htmlcov # specific folder name where coverage always stores HTML reports
          destination: methylcheck
