version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5  # - image: rocker/tidyverse:latest == did not work (req'd password setting first)
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip3 install pipenv
            # BRANCH specific testing of methylprep:
            # pipenv install -e git+https://github.com/FoxoTech/methylprep.git@feature/v1.4.0-bugs#egg=methylprep --skip-lock
            pipenv install -e .[dev] --skip-lock
            pipenv graph
            # This ^^^ installs all the regular required packages and those listed in the dev section of `extras_require` in setup.py.
            # pytest recommends this: install your package in "editable" mode by running this from the same directory.
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Running tests
          command: |
            pipenv install methylprep --skip-lock
            pipenv install coveralls --skip-lock
            pipenv run coverage run setup.py test
      - run:
          name: Coverage
          command: |
            # pipenv run pytest tests --junit-xml=htmlcov/junit.xml # rerun tests to collect test-results | see setup.cfg
            pipenv run coverage report
            pipenv run coverage html
            pipenv run coveralls # -- pushes report to coveralls.io
      - store_test_results:
          path: htmlcov
      - store_artifacts:
          path: htmlcov # specific folder name where coverage always stores HTML reports
          destination: methylcheck
